services:
  # registry
  mvo.survey.registry:
    class: Mvo\ContaoSurvey\Registry

  # entity repositories
  mvo.survey.repository.survey:
    class: Mvo\ContaoSurvey\Repository\SurveyRepository
    arguments:
      - '@doctrine'
    tags:
      - { name: 'doctrine.repository_service' }

  mvo.survey.repository.question:
    class: Mvo\ContaoSurvey\Repository\QuestionRepository
    arguments:
      - '@doctrine'
    tags:
      - { name: 'doctrine.repository_service' }

  mvo.survey.repository.answer:
    class: Mvo\ContaoSurvey\Repository\AnswerRepository
    arguments:
      - '@doctrine'
    tags:
      - { name: 'doctrine.repository_service' }

  mvo.survey.repository.record:
    class: Mvo\ContaoSurvey\Repository\RecordRepository
    arguments:
      - '@doctrine'
    tags:
      - { name: 'doctrine.repository_service' }

  # entity registration
  mvo.survey.listener.class_metadata:
    class: Mvo\ContaoSurvey\EventListener\ClassMetadataListener
    arguments:
      - '@mvo.survey.registry'
    tags:
      - { name: 'doctrine.event_listener', event: 'loadClassMetadata' }

  # form handling
  mvo.survey.session_storage:
    class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
    arguments:
      - 'mvo.survey'
      - '/'

  mvo.survey.form.manager_factory:
    class: Mvo\ContaoSurvey\Form\SurveyManagerFactory
    arguments:
      - '@form.factory'
      - '@mvo.survey.registry'
      - '@mvo.survey.session_storage'

  # form types
  mvo.survey.form.type.survey_step:
    class: Mvo\ContaoSurvey\Form\SurveyStepFormType
    arguments:
      - '@mvo.survey.registry'
    tags:
      - { name: 'form.type' }

  mvo.survey.form.type.matrix:
    class: Mvo\ContaoSurvey\Form\AnswerType\AnswerMatrixType
    tags:
      - { name: 'form.type' }

  mvo.survey.form.type.order:
    class: Mvo\ContaoSurvey\Form\AnswerType\AnswerOrderType
    tags:
      - { name: 'form.type' }

  mvo.survey.form.type.rating:
    class: Mvo\ContaoSurvey\Form\AnswerType\AnswerRatingType
    tags:
      - { name: 'form.type' }

  mvo.survey.form.type.select:
    class: Mvo\ContaoSurvey\Form\AnswerType\AnswerSelectType
    tags:
      - { name: 'form.type' }

  mvo.survey.form.type.text:
    class: Mvo\ContaoSurvey\Form\AnswerType\AnswerTextType
    tags:
      - { name: 'form.type' }

  # reports
  mvo.survey.report.data_collector:
    class: Mvo\ContaoSurvey\Report\DataCollector

  mvo.survey.report.csv_exporter:
    class: Mvo\ContaoSurvey\Report\CsvExporter
    arguments:
      - '@mvo.survey.report.data_collector'
    tags:
      - { name: mvo.survey.report.exporter }

  # contao backend
  Mvo\ContaoSurvey\Controller\BackendHelper:
    public: true
    arguments:
      - '@mvo.survey.repository.question'
      - '@mvo.survey.registry'
      - '@security.helper'

  Mvo\ContaoSurvey\Controller\ExportController:
    public: true
    arguments:
      - '@security.helper'
      - '@mvo.survey.repository.survey'
      - !tagged_locator { tag: 'mvo.survey.report.exporter', default_index_method: 'getExtension' }
      - '@contao.slug.generator'

  Mvo\ContaoSurvey\Controller\SurveyFragment:
    arguments:
      - '@mvo.survey.repository.survey'
      - '@mvo.survey.form.manager_factory'
      - '@contao.routing.scope_matcher'
      - '@doctrine.orm.entity_manager'
      - '@contao.csrf.token_manager'
      - '%contao.csrf_token_name%'
    tags:
      - { name: 'terminal42_service_annotation' }

  mvo.survey.listener.datacontainer.survey:
    class: Mvo\ContaoSurvey\EventListener\DataContainer\Survey
    tags:
      - { name: 'terminal42_service_annotation' }
    arguments:
      - '@mvo.survey.repository.record'

  mvo.survey.listener.datacontainer.section:
    class: Mvo\ContaoSurvey\EventListener\DataContainer\SurveySection
    tags:
      - { name: 'terminal42_service_annotation' }

  mvo.survey.listener.datacontainer.question:
    class: Mvo\ContaoSurvey\EventListener\DataContainer\SurveyQuestion
    tags:
      - { name: 'terminal42_service_annotation' }
    arguments:
      - '@mvo.survey.repository.question'
      - '@mvo.survey.registry'
      - '@translator'
      - '@twig'
